name: test_coverage
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 0.5.0
homepage: https://github.com/pulyaevskiy/test-coverage
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.13.0 <3.0.0'

executables:
  test_coverage:

dependencies:
  coverage: ^1.0.3
  path: ^1.8.0
  lcov:
    git:
      url: https://github.com/AugustToko/lcov.dart.git
  glob: ^2.0.1
  args: ^2.1.0

dev_dependencies:
  test: ^1.17.5
  pedantic: ^1.11.0
